version: "4.0.3"

networks:
  great-network:
    driver: bridge

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "8085:8085"            # LocalStack custom health check
    entrypoint: sh -c "/usr/local/bin/prestart.sh && exec /usr/local/bin/docker-entrypoint.sh localstack"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/shutdown.sh:/etc/localstack/init/shutdown.d/shutdown.sh"
      - "./scripts/prestart.sh:/usr/local/bin/prestart.sh"
      - "./scripts/configure_localstack.sh:/etc/localstack/init/ready.d/script.sh"
      - "./scripts/rotationLambda.zip:/scripts/rotationLambda.zip"
      - "./certs/server.crt:/usr/local/share/ca-certificates/server.crt" # Mount the certificate
      - "./certs/server.key:/usr/local/share/ca-certificates/server.key"
      - "./terraform:/terraform"   # Mount Terraform configuration
    environment:
      - SERVICES=lambda,secretsmanager,sns,iam,sts,ec2 # Enable only required services
      - DOCKER_HOST=unix:///var/run/docker.sock
    healthcheck:
      test: >
        curl --silent --fail http://localhost:8085
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      great-network:
        aliases:
          - localhost.localstack.cloud

  bedrock:
    container_name: bedrock
    build:
      context: target/docker/stage
      dockerfile: Dockerfile
    depends_on:
      localstack:
        condition: service_healthy
    ports:
      - 8073:8073 # Expose your server's port
    volumes:
      - "./certs/server.crt:/certs/server.crt" # Mount the certificate
      - "./certs/server.key:/certs/server.key"
    env_file:
      - "./certs/oauth.env"
    environment:
      - JAVA_OPTS=-Djava.net.preferIPv4Stack=true
      - LOCALSTACK_URL=http://localstack:4566
      - SERVER_CERT_PATH=/certs/server.crt
      - SERVER_KEY_PATH=/certs/server.key
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://bedrock:8073/health"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - great-network

  # debug:
  #   container_name: debug-container
  #   image: ubuntu:latest
  #   entrypoint: ["sleep", "infinity"] # Keeps the container running
  #   tty: true
