version: "4.0.3"

networks:
  great-network:
    driver: bridge

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
    volumes:
#      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/configure_localstack.sh:/etc/localstack/init/ready.d/script.sh"
      - "./scripts/rotationLambda.zip:/scripts/rotationLambda.zip"
      - "./certs/server.crt:/usr/local/share/ca-certificates/server.crt" # Mount the certificate
      - "./certs/server.key:/usr/local/share/ca-certificates/server.key"
    command: >
      sh -c "cp /usr/local/share/ca-certificates/server.crt /etc/ssl/certs/ && 
        cp /usr/local/share/ca-certificates/server.key /etc/ssl/private/ &&
        update-ca-certificates &&
        exec localstack"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      great-network:
        aliases:
          - localhost.localstack.cloud

  bedrock:
    container_name: bedrock
    build:
      context: target/docker/stage
      dockerfile: Dockerfile
    depends_on:
      localstack:
        condition: service_healthy
    ports:
      - 8073:8073 # Expose your server's port
    environment:
      - JAVA_OPTS=-Djava.net.preferIPv4Stack=true
      - LOCALSTACK_URL=http://localstack:4566
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://bedrock:8073/health"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - great-network

  # debug:
  #   container_name: debug-container
  #   image: ubuntu:latest
  #   entrypoint: ["sleep", "infinity"] # Keeps the container running
  #   tty: true
